// <auto-generated />
namespace Parrot.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delta));
        
        string IMigrationMetadata.Id
        {
            get { return "201509031710593_delta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
